"use client";

import SiteHeader from "../components/site-header";
import { useLanguage } from "../components/language-provider";

const content = {
  de: { title: "Datenschutz", sections: [
    ["1. Verantwortlicher", ["Veit Hiller · Colectivo Gráfico Mallorca", "NIE: Y5710911W", "Carrer na Batlessa 10, 07570 Artà, Illes Balears, Spanien", "info@colectivograficomallorca.es"]],
    ["2. Bestellungen und Zahlungen", ["Für die Abwicklung einer Bestellung verarbeiten wir die notwendigen Bestell- und Kontaktdaten, insbesondere Name, E-Mail-Adresse, bestellte Artikel, Betrag sowie gegebenenfalls Rechnungs- und Lieferadresse. Rechtsgrundlage ist die Erfüllung des Kaufvertrags und die Durchführung vorvertraglicher Maßnahmen.", "Zahlungen werden über Stripe abgewickelt. Zahlungsdaten werden unmittelbar von Stripe verarbeitet. Wir erhalten die für Bestellbestätigung, Versand, Erstattung und Buchhaltung notwendigen Zahlungs- und Transaktionsinformationen, jedoch keine vollständigen Kartendaten."]],
    ["3. Versand", ["Soweit für die Zustellung erforderlich, werden Name, Lieferadresse und Versandinformationen an den jeweils eingesetzten Versanddienstleister übermittelt. Die Verarbeitung erfolgt ausschließlich zur Vertragserfüllung."]],
    ["4. Digitale Downloads", ["Bei digitalen Produkten verarbeiten wir E-Mail-Adresse, Bestell- und Zahlungsstatus, um den Download unmittelbar auf der Website oder per E-Mail bereitzustellen."]],
    ["5. Newsletter", ["Für den Newsletter verarbeiten wir ausschließlich die angegebene E-Mail-Adresse sowie den Nachweis der Anmeldung. Die Anmeldung erfolgt nur nach ausdrücklicher Einwilligung. Versand und Verwaltung erfolgen über Resend. Jede Newsletter-E-Mail enthält eine Abmeldemöglichkeit. Die Einwilligung kann jederzeit mit Wirkung für die Zukunft widerrufen werden."]],
    ["6. Technische Daten", ["Beim Aufruf der Website können technisch notwendige Verbindungsdaten wie IP-Adresse, Zeitpunkt, aufgerufene Seite, Browser- und Geräteinformationen in Serverprotokollen verarbeitet werden. Dies dient dem sicheren und stabilen Betrieb der Website. Nicht notwendige Analyse- oder Werbecookies werden nur eingesetzt, wenn dafür zuvor eine Einwilligung eingeholt wurde."]],
    ["7. Empfänger und internationale Übermittlungen", ["Daten erhalten nur Dienstleister, die für Hosting, Zahlungsabwicklung, E-Mail-Versand, Versand oder technische Betreuung erforderlich sind. Dazu können Stripe und Resend gehören. Soweit Daten außerhalb des Europäischen Wirtschaftsraums verarbeitet werden, erfolgt die Übermittlung auf Grundlage eines Angemessenheitsbeschlusses oder geeigneter Garantien wie EU-Standardvertragsklauseln."]],
    ["8. Speicherdauer", ["Bestell-, Zahlungs- und Rechnungsdaten werden entsprechend den gesetzlichen handels- und steuerrechtlichen Aufbewahrungspflichten gespeichert. Newsletterdaten werden bis zur Abmeldung oder zum Widerruf der Einwilligung gespeichert. Technische Protokolldaten werden nur so lange aufbewahrt, wie sie für Sicherheit und Betrieb erforderlich sind."]],
    ["9. Rechte", ["Betroffene Personen haben im gesetzlichen Umfang das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung kann jederzeit widerrufen werden. Anfragen können an info@colectivograficomallorca.es gerichtet werden. Außerdem besteht das Recht, sich bei der Agencia Española de Protección de Datos zu beschweren."]]
  ]},
  es: { title: "Privacidad", sections: [
    ["1. Responsable del tratamiento", ["Veit Hiller · Colectivo Gráfico Mallorca", "NIE: Y5710911W", "Carrer na Batlessa 10, 07570 Artà, Illes Balears, España", "info@colectivograficomallorca.es"]],
    ["2. Pedidos y pagos", ["Para tramitar un pedido tratamos los datos de contacto y compra necesarios, especialmente nombre, correo electrónico, artículos, importe y, cuando corresponda, dirección de facturación y entrega. La base jurídica es la ejecución del contrato y la aplicación de medidas precontractuales.", "Los pagos se procesan mediante Stripe. Stripe trata directamente los datos de pago. Nosotros recibimos la información de pago y transacción necesaria para confirmar, enviar, reembolsar y contabilizar el pedido, pero no los datos completos de la tarjeta."]],
    ["3. Envíos", ["Cuando sea necesario para la entrega, comunicamos el nombre, la dirección y los datos del envío al transportista correspondiente. El tratamiento se realiza exclusivamente para ejecutar el contrato."]],
    ["4. Descargas digitales", ["En los productos digitales tratamos el correo electrónico y el estado del pedido y del pago para facilitar la descarga inmediata en la web o enviarla por correo electrónico."]],
    ["5. Newsletter", ["Para el newsletter tratamos únicamente el correo electrónico facilitado y el comprobante de la suscripción. El alta requiere un consentimiento expreso. El envío y la gestión se realizan mediante Resend. Cada mensaje incluye una opción para darse de baja. El consentimiento puede retirarse en cualquier momento con efectos futuros."]],
    ["6. Datos técnicos", ["Al visitar la web pueden tratarse datos de conexión técnicamente necesarios, como dirección IP, fecha y hora, página solicitada, navegador y dispositivo. Se utilizan para mantener la seguridad y estabilidad del servicio. Las cookies analíticas o publicitarias no necesarias solo se utilizarán después de obtener el consentimiento correspondiente."]],
    ["7. Destinatarios y transferencias internacionales", ["Solo reciben datos los proveedores necesarios para alojamiento, pagos, correo electrónico, transporte o soporte técnico. Entre ellos pueden encontrarse Stripe y Resend. Cuando exista tratamiento fuera del Espacio Económico Europeo, la transferencia se basará en una decisión de adecuación o en garantías apropiadas, como las cláusulas contractuales tipo de la UE."]],
    ["8. Conservación", ["Los datos de pedidos, pagos y facturación se conservan durante los plazos legales mercantiles y fiscales. Los datos del newsletter se mantienen hasta la baja o retirada del consentimiento. Los registros técnicos se conservan únicamente durante el tiempo necesario para la seguridad y funcionamiento del servicio."]],
    ["9. Derechos", ["Las personas interesadas pueden ejercer, dentro de los límites legales, sus derechos de acceso, rectificación, supresión, limitación, portabilidad y oposición. El consentimiento puede retirarse en cualquier momento. Las solicitudes pueden enviarse a info@colectivograficomallorca.es. También puede presentarse una reclamación ante la Agencia Española de Protección de Datos."]]
  ]}
} as const;

export default function Privacy() {
  const { language } = useLanguage();
  const page = content[language];
  return <main><SiteHeader/><section className="text-page legal-copy shell"><p className="eyebrow">Legal</p><h1>{page.title}</h1>{page.sections.map(([heading, paragraphs]) => <section key={heading}><h2>{heading}</h2>{paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}</section></main>;
}
